// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zuyiqkeosmjdugqrfvkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1eWlxa2Vvc21qZHVncXJmdmtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNDY1NzQsImV4cCI6MjA3MDkyMjU3NH0.ZM39BPxKq03DeovDGMIEROWRYilp2MnCGIbwxmDxwIw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});